/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '92bcc5f3-7bcc-4388-b370-5f812902cfce';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "navigate",
    "location": "#navigate"
}, {
    "name": "startScreen",
    "location": "#startScreen"
}];

function startScreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilegrid_2': 'startScreen_mobilegrid_2',
        'mobilegridcell_3': 'startScreen_mobilegridcell_3',
        'backbutton': 'startScreen_backbutton',
        'showbutton': 'startScreen_showbutton',
        'output': 'startScreen_output',
        'mobilegridcell_4': 'startScreen_mobilegridcell_4',
        'mobileimage_22': 'startScreen_mobileimage_22',
        'mobilegridcell_7': 'startScreen_mobilegridcell_7',
        'mobilegridcell_5': 'startScreen_mobilegridcell_5',
        'mobilegridcell_6': 'startScreen_mobilegridcell_6',
        'prompt': 'startScreen_prompt',
        'labelname': 'startScreen_labelname',
        'mobilegridcell_8': 'startScreen_mobilegridcell_8',
        'mobilegridcell_9': 'startScreen_mobilegridcell_9',
        'array_result_list': 'startScreen_array_result_list',
        'array_result_list_item': 'startScreen_array_result_list_item',
        'mobilelistitembutton_49': 'startScreen_mobilelistitembutton_49',
        'mobilegridcell_10': 'startScreen_mobilegridcell_10',
        'labelstreet': 'startScreen_labelstreet',
        'labelcity': 'startScreen_labelcity',
        'labelzip': 'startScreen_labelzip',
        'labelphone': 'startScreen_labelphone',
        'Input': 'startScreen_Input',
        'custom_message_input': 'startScreen_custom_message_input',
        'result_list': 'startScreen_result_list',
        'mobilelistitem_45': 'startScreen_mobilelistitem_45',
        'mobilelistitembutton_46': 'startScreen_mobilelistitembutton_46',
        'mobilegridcell_11': 'startScreen_mobilegridcell_11',
        'mobilegridcell_12': 'startScreen_mobilegridcell_12',
        'mobilegridcell_13': 'startScreen_mobilegridcell_13',
        'optionscheckbox': 'startScreen_optionscheckbox',
        'sendcustommessagecheck': 'startScreen_sendcustommessagecheck',
        'sendetacheck': 'startScreen_sendetacheck',
        'navigatecheck': 'startScreen_navigatecheck',
        'search_button': 'startScreen_search_button',
        'go': 'startScreen_go',
        'mobilegridcell_14': 'startScreen_mobilegridcell_14',
        'mobilegridcell_15': 'startScreen_mobilegridcell_15',
        'mobilegridcell_16': 'startScreen_mobilegridcell_16',
        'sms_return_label': 'startScreen_sms_return_label',
        'eta_body_label': 'startScreen_eta_body_label',
        'message_sent_label': 'startScreen_message_sent_label',
        'mobilegridcell_17': 'startScreen_mobilegridcell_17',
        'mobilegridcell_19': 'startScreen_mobilegridcell_19',
        'mobilegridcell_20': 'startScreen_mobilegridcell_20',
        'mobilegridcell_21': 'startScreen_mobilegridcell_21'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["startScreen_get_user_name_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {

            "to_name": "get_user_name",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "{salesforce_access_token}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["startScreen_get_user_name_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "get_user_name",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "CurrentUser",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['user']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "get_user_name",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "userName",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['user']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_query_project_name_oncomplete_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "candidates_array",
            "from_type": "LOCAL_STORAGE",

            "to_name": "startScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$[i]",
                "target": "$['array_result_list_item']"

            },

            {

                "source": "$[i]['proj_item_name']",
                "target": "$['array_result_list_item:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_query_project_name_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "SearchTerm",
            "from_type": "SESSION_STORAGE",

            "to_name": "query_project_name",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "{salesforce_access_token}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['q']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_query_project_name_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "query_project_name",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "startScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['records'][i]",
                "target": "$['mobilelistitem_45']"

            },

            {

                "source": "$['body']['records'][i]['Name']",
                "target": "$['mobilelistitem_45:text']"

            }

            ]
        },

        {
            "from_name": "query_project_name",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationPhone",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['PrimaryContactPhone__c']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationCity",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['BillingCity']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationState",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['BillingState']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationStreet",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['BillingStreet']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationLat",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['BillingLatitude']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationLng",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['BillingLongitude']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationZip",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['BillingPostalCode']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "candidates_array",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['BillingLongitude']",
                "target": "$[0]['item_dest_lng']"

            },

            {

                "source": "$['body']['records'][0]['Account__r']['BillingLatitude']",
                "target": "$[0]['item_dest_lat']"

            },

            {

                "source": "$['body']['records'][0]['Account__r']['BillingPostalCode']",
                "target": "$[0]['item_zip']"

            },

            {

                "source": "$['body']['records'][0]['Account__r']['BillingState']",
                "target": "$[0]['item_state']"

            },

            {

                "source": "$['body']['records'][0]['Account__r']['PrimaryContactPhone__c']",
                "target": "$[0]['item_phone']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_query_project_name_2_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "DestinationSearchTerm",
            "from_type": "SESSION_STORAGE",

            "to_name": "query_project_name_2",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "{salesforce_access_token}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['q']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_query_project_name_2_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "query_project_name_2",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationProjectName",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Name']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name_2",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationPhone",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['PrimaryContactPhone__c']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name_2",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationCity",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['BillingCity']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name_2",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationState",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['BillingState']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name_2",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationStreet",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['BillingStreet']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name_2",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationLat",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['BillingLatitude']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name_2",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationLng",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['BillingLongitude']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name_2",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationZip",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['BillingPostalCode']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "query_project_name_2",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "startScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Name']",
                "target": "$['labelname:text']"

            },

            {

                "source": "$['body']['records'][0]['Account__r']['BillingStreet']",
                "target": "$['labelstreet:text']"

            },

            {

                "source": "$['body']['records'][0]['Account__r']['BillingCity']",
                "target": "$['labelcity:text']"

            },

            {

                "source": "$['body']['records'][0]['Account__r']['BillingPostalCode']",
                "target": "$['labelzip:text']"

            },

            {

                "source": "$['body']['records'][0]['Account__r']['PrimaryContactPhone__c']",
                "target": "$['labelphone:text']"

            }

            ]
        },

        {
            "from_name": "query_project_name_2",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "DestinationName",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['records'][0]['Account__r']['Name']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_geolocation1_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {

            "to_name": "geolocation1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "maximumAge": 3000,
                        "timeout": 5000,
                        "enableHighAccuracy": true,
                        "watchPosition": false
                    }
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["startScreen_geolocation1_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "geolocation1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "currentLat",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['data']['coords']['latitude']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "geolocation1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "currentLng",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['data']['coords']['longitude']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_eta_service_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "eta_service",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "ReturnTextMessage",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['ETA']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "eta_service",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "MessageResult",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['SMSstatus']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "eta_service",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "startScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['SMSstatus']",
                "target": "$['sms_return_label:text']"

            },

            {

                "source": "$['body']['ETA']",
                "target": "$['eta_body_label:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_eta_service_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "DestinationProjectName",
            "from_type": "SESSION_STORAGE",

            "to_name": "eta_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "BASIC YXNhcDptYW5hZ2VpdA==",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "CustomerPhone": "8016233381",
                    "Host": "Sandbox"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['Project']"

            }

            ]
        },

        {
            "from_name": "currentLat",
            "from_type": "SESSION_STORAGE",

            "to_name": "eta_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "BASIC YXNhcDptYW5hZ2VpdA==",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "CustomerPhone": "8016233381",
                    "Host": "Sandbox"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['StartLat']"

            }

            ]
        },

        {
            "from_name": "currentLng",
            "from_type": "SESSION_STORAGE",

            "to_name": "eta_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "BASIC YXNhcDptYW5hZ2VpdA==",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "CustomerPhone": "8016233381",
                    "Host": "Sandbox"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['StartLng']"

            }

            ]
        },

        {
            "from_name": "DestinationLng",
            "from_type": "SESSION_STORAGE",

            "to_name": "eta_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "BASIC YXNhcDptYW5hZ2VpdA==",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "CustomerPhone": "8016233381",
                    "Host": "Sandbox"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['DestLng']"

            }

            ]
        },

        {
            "from_name": "DestinationLat",
            "from_type": "SESSION_STORAGE",

            "to_name": "eta_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "BASIC YXNhcDptYW5hZ2VpdA==",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "CustomerPhone": "8016233381",
                    "Host": "Sandbox"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['DestLat']"

            }

            ]
        },

        {
            "from_name": "CustomMessage",
            "from_type": "SESSION_STORAGE",

            "to_name": "eta_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "BASIC YXNhcDptYW5hZ2VpdA==",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "CustomerPhone": "8016233381",
                    "Host": "Sandbox"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['CustomMsg']"

            }

            ]
        },

        {
            "from_name": "SendETA",
            "from_type": "SESSION_STORAGE",

            "to_name": "eta_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "BASIC YXNhcDptYW5hZ2VpdA==",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "CustomerPhone": "8016233381",
                    "Host": "Sandbox"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['NotifyCustomer']"

            }

            ]
        },

        {
            "from_name": "SendCustomOnly",
            "from_type": "SESSION_STORAGE",

            "to_name": "eta_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "BASIC YXNhcDptYW5hZ2VpdA==",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "CustomerPhone": "8016233381",
                    "Host": "Sandbox"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['SendCustomOnly']"

            }

            ]
        },

        {
            "from_name": "CurrentUser",
            "from_type": "SESSION_STORAGE",

            "to_name": "eta_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "BASIC YXNhcDptYW5hZ2VpdA==",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "CustomerPhone": "8016233381",
                    "Host": "Sandbox"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['User']"

            }

            ]
        },

        {
            "from_name": "DestinationName",
            "from_type": "SESSION_STORAGE",

            "to_name": "eta_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "BASIC YXNhcDptYW5hZ2VpdA==",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "CustomerPhone": "8016233381",
                    "Host": "Sandbox"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['CustomerName']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.get_user_name = Apperyio.datasources.get_user_name = new Apperyio.DataSource(getUser, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_get_user_name_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_get_user_name_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            alert('User Name not returned!!');
        }
    });

    window.query_project_name = Apperyio.datasources.query_project_name = new Apperyio.DataSource(Suncrest_project_query_service_test, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_query_project_name_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_query_project_name_oncomplete_mapping_0"]);

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_query_project_name_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            alert('Project not found');
        }
    });

    window.query_project_name_2 = Apperyio.datasources.query_project_name_2 = new Apperyio.DataSource(Suncrest_project_query_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_query_project_name_2_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_query_project_name_2_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            alert('Error: Project not found');
        }
    });

    window.geolocation1 = Apperyio.datasources.geolocation1 = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_geolocation1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_geolocation1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            alert('Error: Geolocation not locating!!!');
        }
    });

    window.eta_service = Apperyio.datasources.eta_service = new Apperyio.DataSource(ETAService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_eta_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            alert('Message Result: ' + sessionStorage.getItem('MessageResult') + ', ETA: ' + sessionStorage.getItem('ReturnTextMessage'));

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_eta_service_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            alert('Error: ETA service not working');
        }
    });

    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            Apperyio('street').val(null);
            Apperyio('search_button').val(true);
            sessionStorage.setItem('CustomMessage', 'Have a Great DAy!!');
            sessionStorage.setItem('SearchTerm', null);
            sessionStorage.setItem('DestinationProjectName', null);
            sessionStorage.setItem('Project', null);
            sessionStorage.setItem('DestinationCity', null);
            sessionStorage.setItem('DestinationLat', null);
            sessionStorage.setItem('DestinationLng', null);
            sessionStorage.setItem('DestinationStreet', null);
            sessionStorage.setItem('DestinationZip', null);
            sessionStorage.setItem('DestinationState', null);
            sessionStorage.setItem('DestinationPhone', null);
            sessionStorage.setItem('DestinationSearchTerm', null);
            sessionStorage.setItem('DestinationName', null);
            sessionStorage.setItem('SendMessage', 'Yes');
            sessionStorage.setItem('SendETA', 'Yes');
            sessionStorage.setItem('Navigate', 'Yes');
            sessionStorage.setItem('ETA', null);
            sessionStorage.setItem('DestinationAddress', null);
            sessionStorage.setItem('markerLat', null);
            sessionStorage.setItem('markerLng', null);
            sessionStorage.setItem('currentLat', null);
            sessionStorage.setItem('currentLng', null);
            sessionStorage.setItem('SendCustomOnly', 'No');
            sessionStorage.setItem('showAddress', null);
            sessionStorage.setItem('CurrentAddress', null);
            sessionStorage.setItem('dateTime', null);

            sessionStorage.setItem('Distance', null);
            sessionStorage.setItem('Duration', null);
            sessionStorage.setItem('MessageResult', 'N/A');

            sessionStorage.setItem('ReturnTextMessage', 'N/A');

            //alert('RefreshStartVariables complete');
            salesforceLogin();;

            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events


    function startScreen_windowEvents() {

        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code

        /* array_result_list */

        listView = $("#startScreen_array_result_list");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#startScreen_array_result_list .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* array_result_list_item */

        /* result_list */

        listView = $("#startScreen_result_list");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#startScreen_result_list .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_45 */

    };

    // screen elements handler


    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#startScreen_mobilecontainer [name="backbutton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.location.reload();

                }
            },
        }, '#startScreen_mobilecontainer [name="backbutton"]');
        $(document).off("click", '#startScreen_mobilecontainer [name="showbutton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.c15r("output", "set", "text", $a.storage["salesforce_access_Token"].get("$"))
                    } catch (e) {
                        console.error(e)
                    };

                }
            },
        }, '#startScreen_mobilecontainer [name="showbutton"]');

        $(document).off("change", '#startScreen_mobilecontainer [name="Input"]').on({
            change: function(event) {
                try {
                    $a.storage["SearchTerm"].update("$", "null")
                } catch (e) {
                    console.error(e)
                };
            },
        }, '#startScreen_mobilecontainer [name="Input"]');

        $(document).off("click", '#startScreen_mobilecontainer [name="mobilelistitem_45"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["DestinationProjectName"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('mobilelistitem_45', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    sessionStorage.setItem('DestinationSearchTerm', null);
                    var searchString = "SELECT Name,Account__r.Name,Account__r.PrimaryContactPhone__c,Account__r.BillingCity,Account__r.BillingState,Account__r.BillingStreet,Account__r.BillingLatitude,Account__r.BillingLongitude,Account__r.BillingPostalCode FROM Project__c WHERE Name LIKE '" + sessionStorage.getItem('DestinationProjectName') + "%' LIMIT 1";
                    sessionStorage.setItem('DestinationSearchTerm', searchString);
                    try {
                        query_project_name.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    toggle('startScreen_result_list', 'mob', 'false');
                    toggle('startScreen_optionscheckbox', 'mob', 'true');
                    toggle('startScreen_labelcity', 'mob', 'true');
                    toggle('startScreen_labelname', 'mob', 'true');
                    toggle('startScreen_labelphone', 'mob', 'true');
                    toggle('startScreen_labelstreet', 'mob', 'true');
                    toggle('startScreen_labelzip', 'mob', 'true');
                    try {
                        $a.c15r("labelcity", "set", "text", $a.storage["DestinationCity"].get("$"))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.c15r("labelname", "set", "text", $a.storage["DestinationProjectName"].get("$"))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.c15r("labelphone", "set", "text", $a.storage["DestinationPhone"].get("$"))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.c15r("labelstreet", "set", "text", $a.storage["DestinationStreet"].get("$"))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.c15r("labelzip", "set", "text", $a.storage["DestinationZip"].get("$"))
                    } catch (e) {
                        console.error(e)
                    };
                    toggle('startScreen_go', 'mob', 'true');
                    try {
                        geolocation1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    try {
                        get_user_name.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    toggle('startScreen_custom_message_input', 'mob', 'true');
                    try {
                        $a.c15r("prompt", "set", "text", 'double-check project information:')
                    } catch (e) {
                        console.error(e)
                    };

                }
            },
        }, '#startScreen_mobilecontainer [name="mobilelistitem_45"]');

        $(document).off("focus", '#startScreen_mobilecontainer [name="sendcustommessagecheck"]').on({
            focus: function(event) {
                var x = sessionStorage.getItem('SendMessage');
                alert('SendMessage value before= ' + x);
                if (x == 'No') {
                    x = 'Yes';
                    sessionStorage.setItem('SendMessage', 'Yes');
                } else {
                    x = 'No';
                    sessionStorage.setItem('SendMessage', 'No');
                };
            },
        }, '#startScreen_mobilecontainer [name="sendcustommessagecheck"]');
        $(document).off("change", '#startScreen_mobilecontainer [name="sendetacheck"]').on({
            change: function(event) {
                var x = sessionStorage.getItem('SendETA');
                alert('SendETA value before= ' + x);
                if (x == 'No') {
                    //alert('Yes send ETA');
                    x = 'Yes';
                    sessionStorage.setItem('SendETA', 'Yes');
                } else {
                    // alert('no send ETA');
                    x = 'No';
                    sessionStorage.setItem('SendETA', 'No');
                };
            },
        }, '#startScreen_mobilecontainer [name="sendetacheck"]');
        $(document).off("change", '#startScreen_mobilecontainer [name="navigatecheck"]').on({
            change: function(event) {
                var x = sessionStorage.getItem('Navigate');
                alert('Navigate value before= ' + x);
                if (x == 'No') {
                    x = 'Yes';
                    sessionStorage.setItem('Navigate', 'Yes');
                } else {
                    x = 'No';
                    sessionStorage.setItem('Navigate', 'No');
                };
            },
        }, '#startScreen_mobilecontainer [name="navigatecheck"]');
        $(document).off("click", '#startScreen_mobilecontainer [name="search_button"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    sessionStorage.setItem('DestinationProjectName', null);
                    sessionStorage.setItem('Project', null);
                    sessionStorage.setItem('DestinationCity', null);
                    sessionStorage.setItem('DestinationLat', null);
                    sessionStorage.setItem('DestinationLng', null);
                    sessionStorage.setItem('DestinationStreet', null);
                    sessionStorage.setItem('DestinationZip', null);
                    sessionStorage.setItem('DestinationState', null);
                    sessionStorage.setItem('DestinationPhone', null);
                    sessionStorage.setItem('DestinationSearchTerm', null);
                    sessionStorage.setItem('DestinationName', null);
                    var input = Apperyio('Input').val();
                    var searchString = "SELECT Name,Account__r.Name,Account__r.PrimaryContactPhone__c,Account__r.BillingCity,Account__r.BillingState,Account__r.BillingStreet,Account__r.BillingLatitude,Account__r.BillingLongitude,Account__r.BillingPostalCode FROM Project__c WHERE Name LIKE '%" + input + "%' LIMIT 15";
                    sessionStorage.setItem('SearchTerm', searchString);

                    ;
                    try {
                        query_project_name.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    toggle('startScreen_Input', 'mob', 'false');
                    try {
                        $a.c15r("prompt", "set", "text", 'Choose project below')
                    } catch (e) {
                        console.error(e)
                    };
                    toggle('startScreen_search_button', 'mob', 'false');
                    toggle('startScreen_result_list', 'mob', 'true');
                    toggle('startScreen_backbutton', 'mob', 'true');

                }
            },
        }, '#startScreen_mobilecontainer [name="search_button"]');
        $(document).off("click", '#startScreen_mobilecontainer [name="go"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var x = sessionStorage.getItem('Navigate'); //checkbox checked              
                    var y = sessionStorage.getItem('SendMessage'); //checkbox checked 
                    var z = sessionStorage.getItem('SendETA'); //checkbox checked 
                    sessionStorage.setItem('CustomMessage', Apperyio('custom_message_input').val());
                    var maps = localStorage.getItem('DestinationAddress');
                    //encodes the string into url syntax
                    var res = encodeURI(maps);
                    alert(x + y + z);
                    //navigate,send message,send eta
                    if (x === 'Yes' && y === 'Yes' && z === 'Yes') {
                        //alert('varx= '+x+', vary= '+y+', varz= '+z);
                        sessionStorage.setItem('SendETA', 'Yes');
                        eta_service.execute({});
                        window.open(res); //navigates
                    }

                    //navigate and send message no eta
                    if (x === 'Yes' && y === 'Yes' && z === 'No') {

                        var input = Apperyio('custom_message_input').val(); //sending message
                        sessionStorage.setItem('SendETA', 'Yes');
                        sessionStorage.setItem('CustomMessage', input);
                        eta_service.execute({});
                        window.open(res); //navigating
                    }

                    //navigate only
                    if (x === 'Yes' && y === 'No' && z === 'No') {
                        window.open(res); //navigating
                    }

                    //navigate and send eta
                    if (x === 'Yes' && y === 'No' && z === 'Yes') {
                        sessionStorage.setItem('SendETA', 'Yes');
                        eta_service.execute({});
                        window.open(res); //navigates
                    }

                    //send message only 
                    if (x === 'No' && y === 'Yes' && z === 'No') {
                        var input = Apperyio('custom_message_input').val();
                        sessionStorage.setItem('CustomMessage', input);
                        sessionStorage.setItem('SendCustomOnly', 'Yes');
                        eta_service.execute({});

                    }
                    //send message & eta
                    if (x === 'No' && y === 'Yes' && z === 'Yes') {
                        var input = Apperyio('custom_message_input').val();
                        sessionStorage.setItem('SendETA', 'Yes');
                        sessionStorage.setItem('CustomMessage', input);
                        eta_service.execute({});

                    }

                    //send eta only
                    if (x === 'No' && y === 'No' && z === 'Yes') {
                        sessionStorage.setItem('SendETA', 'Yes');
                        eta_service.execute({});

                    }

                    //1 box must be checked
                    if (x === 'No' && y === 'No' && z === 'No') {
                        alert("At least 1 box must be checked...");
                    };
                    try {
                        $a.c15r("message_sent_label", "set", "text", $a.storage["CustomMessage"].get("$"))
                    } catch (e) {
                        console.error(e)
                    };

                }
            },
        }, '#startScreen_mobilecontainer [name="go"]');

    };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    startScreen_onLoad();
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});

function navigate_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilegrid_22': 'navigate_mobilegrid_22',
        'mobilegridcell_23': 'navigate_mobilegridcell_23',
        'back_button': 'navigate_back_button',
        'mobilegridcell_24': 'navigate_mobilegridcell_24',
        'smsoutput': 'navigate_smsoutput',
        'mobilegridcell_27': 'navigate_mobilegridcell_27',
        'map': 'navigate_map',
        'current_position': 'navigate_current_position',
        'mobilegrid_6': 'navigate_mobilegrid_6',
        'mobilegridcell_7': 'navigate_mobilegridcell_7',
        'mobilegridcell_8': 'navigate_mobilegridcell_8',
        'mobilelabel_5': 'navigate_mobilelabel_5',
        'mobilegridcell_17': 'navigate_mobilegridcell_17',
        'mobilegridcell_9': 'navigate_mobilegridcell_9',
        'mobilegridcell_10': 'navigate_mobilegridcell_10',
        'mobilebutton_4': 'navigate_mobilebutton_4',
        'show_the_eta': 'navigate_show_the_eta',
        'mobilegridcell_18': 'navigate_mobilegridcell_18',
        'mobilegridcell_11': 'navigate_mobilegridcell_11',
        'mobilegridcell_12': 'navigate_mobilegridcell_12',
        'eta_ouput': 'navigate_eta_ouput',
        'mobilegridcell_19': 'navigate_mobilegridcell_19',
        'mobilegridcell_13': 'navigate_mobilegridcell_13',
        'mobilegridcell_14': 'navigate_mobilegridcell_14',
        'mobilegridcell_20': 'navigate_mobilegridcell_20',
        'mobilegridcell_15': 'navigate_mobilegridcell_15',
        'mobilegridcell_16': 'navigate_mobilegridcell_16',
        'mobilegridcell_21': 'navigate_mobilegridcell_21'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["navigate_navigate_onload_mapping_1"] = {
        "homeScreen": "navigate",
        "directions": [

        {
            "from_name": "DestinationLat",
            "from_type": "SESSION_STORAGE",

            "to_name": "navigate",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$",
                "target": "$['map:latitude']"

            },

            {

                "source": "$",
                "target": "$['current_position:latitude']"

            }

            ]
        },

        {
            "from_name": "DestinationLng",
            "from_type": "SESSION_STORAGE",

            "to_name": "navigate",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$",
                "target": "$['map:longitude']"

            },

            {

                "source": "$",
                "target": "$['current_position:longitude']"

            }

            ]
        },

        {
            "from_name": "showAddress",
            "from_type": "SESSION_STORAGE",

            "to_name": "navigate",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$",
                "target": "$['mobilelabel_5:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["navigate_convert_address_onbeforesend_mapping_0"] = {
        "homeScreen": "navigate",
        "directions": [

        {

            "to_name": "convert_address",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "sensor": "false"
                },
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["navigate_convert_address_onsuccess_mapping_0"] = {
        "homeScreen": "navigate",
        "directions": [

        {
            "from_name": "convert_address",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "currentLat",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['results'][0]['geometry']['location']['lat']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "convert_address",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "currentLng",
            "to_type": "SESSION_STORAGE",

            "mappings": [

            {

                "source": "$['body']['results'][0]['geometry']['location']['lng']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["navigate_etaservice_onbeforesend_mapping_0"] = {
        "homeScreen": "navigate",
        "directions": [

        {

            "to_name": "etaservice",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "BASIC YXNhcDptYW5hZ2VpdA==",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "parameters": {},
                "body": {
                    "CustomerPhone": "8016233381",
                    "Host": "Sandbox"
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["navigate_etaservice_onsuccess_mapping_0"] = {
        "homeScreen": "navigate",
        "directions": []
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.convert_address = Apperyio.datasources.convert_address = new Apperyio.DataSource(ConvertAddress, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["navigate_convert_address_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["navigate_convert_address_onsuccess_mapping_0"]);

            var markerLatLng = new google.maps.LatLng(localStorage.getItem('markerLat'), localStorage.getItem('markerLng'));

            var marker = new google.maps.Marker({
                position: markerLatLng,
                map: map,
                title: data.results[0].address_components[0].long_name,
                animation: google.maps.Animation.DROP
            });

            bounds.extend(markerLatLng);
            map.fitBounds(bounds);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.etaservice = Apperyio.datasources.etaservice = new Apperyio.DataSource(ETAService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["navigate_etaservice_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["navigate_etaservice_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'navigate';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var navigate_onLoad = function() {
            navigate_elementsExtraJS();

            var address = 'https://maps.google.com/maps?language=en_US&q=' + localStorage.getItem('DestinationStreet') + ',' + localStorage.getItem('DestinationCity') + ',' + localStorage.getItem('DestinationState') + ',' + localStorage.getItem('DestinationZip') + ', US';

            var showAddress = localStorage.getItem('DestinationStreet') + ',' + localStorage.getItem('DestinationCity') + ',' + localStorage.getItem('DestinationState') + ',' + localStorage.getItem('DestinationZip') + ',' + localStorage.getItem('DestinationPhone');
            localStorage.setItem('DestinationAddress', address);
            localStorage.setItem('showAddress', showAddress);

            ;
            Apperyio.processMappingAction(Apperyio.mappings["navigate_navigate_onload_mapping_1"]);
            try {
                $a.c15r("smsoutput", "set", "text", $a.storage["ReturnTextMessage"].get("$"))
            } catch (e) {
                console.error(e)
            };

            navigate_deviceEvents();
            navigate_windowEvents();
            navigate_elementsEvents();
        };

    // screen window events


    function navigate_windowEvents() {

        $('#navigate').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function navigate_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function navigate_elementsExtraJS() {
        // screen (navigate) extra code

        /* map */

        $("[name = 'map']").wrap("<div/>");
        $("[name = 'map']").parent().css("margin-left", $("[name = 'map']").css("margin-left"));
        $("[name = 'map']").parent().css("margin-right", $("[name = 'map']").css("margin-right"));
        $("[name = 'map']").css("margin-left", '0');
        $("[name = 'map']").css("margin-right", '0');

        var map_options = {
            markerSourceName: "map_markers",
            latitude: "",
            longitude: "",
            address: "",
            zoom: 18,
            showLocationMarker: true
        }

        Apperyio.__registerComponent('map', new Apperyio.ApperyMapComponent("map", map_options));
        $("[name='map_markers'] [apperytype='marker']").attr("reRender", "map");
        $(":mobile-pagecontainer").off("pagecontainershow.navigate_mobilecontainer").on("pagecontainershow.navigate_mobilecontainer", function(event, ui) {
            if (($('#navigate_map', ui.toPage).length > 0) && (Apperyio('map') != undefined)) {
                Apperyio('map').refresh();
            }
        });

    };

    // screen elements handler


    function navigate_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#navigate_mobilecontainer [name="back_button"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    setTimeout(function() {
                        window.location = '#startScreen';
                    }, 0);

                }
            },
        }, '#navigate_mobilecontainer [name="back_button"]');

        $(document).off("click", '#navigate_mobilecontainer [name="mobilebutton_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var maps = localStorage.getItem('DestinationAddress');
                    //encodes the string into url syntax
                    var res = encodeURI(maps);
                    window.open(res);

                }
            },
        }, '#navigate_mobilecontainer [name="mobilebutton_4"]');
        $(document).off("click", '#navigate_mobilecontainer [name="show_the_eta"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.c15r("eta_ouput", "set", "text", $a.storage["ETA"].get("$"))
                    } catch (e) {
                        console.error(e)
                    };

                }
            },
        }, '#navigate_mobilecontainer [name="show_the_eta"]');

    };

    $(document).off("pagebeforeshow", "#navigate").on("pagebeforeshow", "#navigate", function(event, ui) {
        Apperyio.CurrentScreen = "navigate";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    navigate_onLoad();
};

$(document).off("pagecreate", "#navigate").on("pagecreate", "#navigate", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    navigate_js();
});